force-app/main/default/objects/Attendance__c/Attendance__c.object-meta.xml
<CustomObject>
    <label>Attendance</label>
    <nameField>
        <displayFormat>Att-{0000}</displayFormat>
        <label>Attendance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendance__c/fields/Check_In_Time__c.field-meta.xml
<CustomField>
    <fullName>Check_In_Time__c</fullName>
    <label>Check-In Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Present</fullName>
            </value>
            <value>
                <fullName>Absent</fullName>
                <default>true</default>
                <label>Absent</label>
            </value>
            <value>
                <fullName>Leave - In Approval</fullName>
            </value>
            <value>
                <fullName>Leave - Approved</fullName>
            </value>
            <value>
                <fullName>Holiday</fullName>
            </value>
            <value>
                <fullName>Week-Off</fullName>
            </value>
            <value>
                <fullName>Casual Leave</fullName>
            </value>
            <value>
                <fullName>Sick Leave</fullName>
            </value>
            <value>
                <fullName>Half Day</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Attendance1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/markAttendanceController_Test.cls
@isTest
public class markAttendanceController_Test {
    @isTest
    public static void method1(){
        Time checkTime=Time.newInstance(12, 20, 00,00);
        Datetime NewDate= Datetime.newInstance(System.today(), checkTime);
        Attendance__c attendanceObj= new Attendance__c();
        attendanceObj.Status__c='Absent';
        attendanceObj.User__c=UserInfo.getUserId();
        attendanceObj.Check_In_Time__c= NewDate;
        attendanceObj.Date__c= system.today();
        insert attendanceObj;
        
        test.startTest();
        markAttendanceController.markAttendanceMethod();
        test.stopTest();
    }
}