force-app/main/default/objects/Attendance__c/Attendance__c.object-meta.xml
<CustomObject>
    <label>Attendance</label>
    <nameField>
        <displayFormat>Att-{0000}</displayFormat>
        <label>Attendance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendance__c/fields/Cut_off_Time__c.field-meta.xml
<CustomField>
    <fullName>Cut_off_Time__c</fullName>
    <label>Cut-off Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Present</fullName>
            </value>
            <value>
                <fullName>Absent</fullName>
                <default>true</default>
                <label>Absent</label>
            </value>
            <value>
                <fullName>Leave - In Approval</fullName>
            </value>
            <value>
                <fullName>Leave - Approved</fullName>
            </value>
            <value>
                <fullName>Holiday</fullName>
            </value>
            <value>
                <fullName>Week-Off</fullName>
            </value>
            <value>
                <fullName>Casual Leave</fullName>
            </value>
            <value>
                <fullName>Sick Leave</fullName>
            </value>
            <value>
                <fullName>Half Day</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Attendance1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Userwise_Working_Day__c.field-meta.xml
<CustomField>
    <fullName>Userwise_Working_Day__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Userwise Working Day</label>
    <referenceTo>Userwise_Working_Day__c</referenceTo>
    <relationshipLabel>Attendance</relationshipLabel>
    <relationshipName>Attendance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Holiday_Calander__c/Holiday_Calander__c.object-meta.xml
<CustomObject>
    <label>Holiday Calander</label>
    <nameField>
        <label>Holiday Calander Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Holiday Calanders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Holiday_Calander__c/fields/Holiday_Dates__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Dates__c</fullName>
    <label>Holiday Dates</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Holiday_Calander__c/fields/Holiday_Month__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Month__c</fullName>
    <label>Holiday Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>January</fullName>
            </value>
            <value>
                <fullName>February</fullName>
            </value>
            <value>
                <fullName>March</fullName>
            </value>
            <value>
                <fullName>April</fullName>
            </value>
            <value>
                <fullName>May</fullName>
            </value>
            <value>
                <fullName>June</fullName>
            </value>
            <value>
                <fullName>July</fullName>
            </value>
            <value>
                <fullName>August</fullName>
            </value>
            <value>
                <fullName>September</fullName>
            </value>
            <value>
                <fullName>October</fullName>
            </value>
            <value>
                <fullName>November</fullName>
            </value>
            <value>
                <fullName>December</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Holiday_Calander__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
            <value>
                <fullName>2034</fullName>
            </value>
            <value>
                <fullName>2035</fullName>
            </value>
            <value>
                <fullName>2036</fullName>
            </value>
            <value>
                <fullName>2037</fullName>
            </value>
            <value>
                <fullName>2038</fullName>
            </value>
            <value>
                <fullName>2039</fullName>
            </value>
            <value>
                <fullName>2040</fullName>
            </value>
            <value>
                <fullName>2041</fullName>
            </value>
            <value>
                <fullName>2042</fullName>
            </value>
            <value>
                <fullName>2043</fullName>
            </value>
            <value>
                <fullName>2044</fullName>
            </value>
            <value>
                <fullName>2045</fullName>
            </value>
            <value>
                <fullName>2046</fullName>
            </value>
            <value>
                <fullName>2047</fullName>
            </value>
            <value>
                <fullName>2048</fullName>
            </value>
            <value>
                <fullName>2049</fullName>
            </value>
            <value>
                <fullName>2050</fullName>
            </value>
            <value>
                <fullName>2051</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Holiday_Calander__c/fields/Zone__c.field-meta.xml
<CustomField>
    <fullName>Zone__c</fullName>
    <label>Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>South-AP &amp; TS</fullName>
            </value>
            <value>
                <fullName>South-Tamilnadu</fullName>
            </value>
            <value>
                <fullName>South-Karnataka</fullName>
            </value>
            <value>
                <fullName>South-Kerala</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Zone__c.field-meta.xml
<CustomField>
    <fullName>Zone__c</fullName>
    <label>Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>South-Kerala</fullName>
            </value>
            <value>
                <fullName>South-Karnataka</fullName>
            </value>
            <value>
                <fullName>South-Tamilnadu</fullName>
            </value>
            <value>
                <fullName>South-AP &amp; TS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Userwise_Working_Day__c/Userwise_Working_Day__c.object-meta.xml
<CustomObject>
    <label>Userwise Working Day</label>
    <nameField>
        <label>Parent Attendance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Userwise Working Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Userwise_Working_Day__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Userwise_Working_Days</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Userwise_Working_Day__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
            <value>
                <fullName>2034</fullName>
            </value>
            <value>
                <fullName>2035</fullName>
            </value>
            <value>
                <fullName>2036</fullName>
            </value>
            <value>
                <fullName>2037</fullName>
            </value>
            <value>
                <fullName>2038</fullName>
            </value>
            <value>
                <fullName>2039</fullName>
            </value>
            <value>
                <fullName>2040</fullName>
            </value>
            <value>
                <fullName>2041</fullName>
            </value>
            <value>
                <fullName>2042</fullName>
            </value>
            <value>
                <fullName>2043</fullName>
            </value>
            <value>
                <fullName>2044</fullName>
            </value>
            <value>
                <fullName>2045</fullName>
            </value>
            <value>
                <fullName>2046</fullName>
            </value>
            <value>
                <fullName>2047</fullName>
            </value>
            <value>
                <fullName>2048</fullName>
            </value>
            <value>
                <fullName>2049</fullName>
            </value>
            <value>
                <fullName>2050</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CreateDailyAttendance.cls
public class CreateDailyAttendance implements Database.Batchable<sObject> , Schedulable {
    
    public void execute(SchedulableContext ctx) {
        
        Id batchId = Database.executeBatch(new CreateDailyAttendance());
    }
    
    public List<User> start(Database.BatchableContext bc) {
        
        Set<Id> permissionSetIds = new Set<Id>();
        
        for (SetupEntityAccess access : [SELECT ParentId FROM SetupEntityAccess WHERE SetupEntityId IN 
                                         (SELECT Id FROM CustomPermission WHERE DeveloperName = 'Mark_Attendance')]) {
                                             permissionSetIds.add(access.ParentId);
                                         }
        
        return [SELECT Username,Zone__c, email FROM User WHERE isActive = True AND Id IN (SELECT AssigneeId FROM PermissionSetAssignment WHERE PermissionSetId IN :permissionSetIds)];
    }
    
    public void execute(Database.BatchableContext bc, List<User> records){
        Date currentDate = system.today();
        Set<Id> userIds = new Set<Id>();
        List<Attendance__c> todayAttendanceList = [Select Id, Name, Date__c,User__c FROM Attendance__c WHERE Date__c =: currentDate];
        List<Attendance__c> attendanceLst = new List<Attendance__c>();
        List<Userwise_Working_Day__c> uwDays = [Select Id,Name,User__c,Year__c FROM Userwise_Working_Day__c WHERE Year__c =: string.valueOf(currentDate.year())];
        system.debug('uwDays'+uwDays);
        
        Map<Id,Userwise_Working_Day__c> uwMap = new Map<Id,Userwise_Working_Day__c>();
        for(Userwise_Working_Day__c uw : uwDays){
            uwMap.put(uw.User__c,uw);
        }
        system.debug('uwMap:- '+uwMap);
        for(Attendance__c att : todayAttendanceList){
            userIds.add(att.User__c);
        }
        List<Holiday_Calander__c> holidayList = [Select Id,Name,Holiday_Month__c,Zone__c,Holiday_Dates__c
                                                 FROM Holiday_Calander__c
                                                 WHERE Holiday_Month__c =: String.valueOf(system.today().month())];
        Map<Date,List<String>> hcMap = new Map<Date,List<String>>();
        for(Holiday_Calander__c hc : holidayList){
            List<String> splitDate = hc.Holiday_Dates__c.split(';');
            List<String> zoneList = hc.Zone__c.split(';');
            for(String d : splitDate){
                Date todayDate = date.newinstance(system.today().year(), Integer.valueOf(hc.Holiday_Month__c), Integer.valueOf(d));
                system.debug('todayDate----'+todayDate);
                hcMap.put(todayDate,zoneList);
            }
        }
        DateTime myDateTime = system.now();
        String dayOfWeek = myDateTime.format('E');
        List<String> strList = (System.Label.Week_Off).split(',');
        
        
        for(User user: records){
            system.debug('user----'+user);
            if(!userIds.contains(user.Id)){
                if(uwMap.get(user.Id) != Null){
                    if(!strList.contains(dayOfWeek)){
                        if(hcMap.get(system.today()) != Null){
                            if(hcMap.get(system.today()).contains(user.Zone__c )){                        
                                Attendance__c attendance = new Attendance__c();
                                Time cutOffTime = Time.newInstance(09, 45, 00, 00);
                                attendance.User__c = user.Id;
                                attendance.Date__c = Date.today();
                                attendance.Status__c = 'Holiday';
                                attendance.Email__c = user.email;
                                attendance.Userwise_Working_Day__c = uwMap.get(user.Id).Id;
                                attendance.Cut_off_Time__c = cutOffTime;
                                attendanceLst.add(attendance);
                            }
                            else{
                                Attendance__c attendance = new Attendance__c();
                                Time cutOffTime = Time.newInstance(09, 45, 00, 00);
                                attendance.User__c = user.Id;
                                attendance.Date__c = Date.today();
                                attendance.Status__c = 'Absent';
                                attendance.Email__c = user.email;
                                attendance.Userwise_Working_Day__c = uwMap.get(user.Id).Id;
                                attendance.Cut_off_Time__c = cutOffTime;
                                attendanceLst.add(attendance);
                            }
                        }
                        else{
                            Attendance__c attendance = new Attendance__c();
                            Time cutOffTime = Time.newInstance(09, 45, 00, 00);
                            attendance.User__c = user.Id;
                            attendance.Date__c = Date.today();
                            attendance.Status__c = 'Absent';
                            attendance.Email__c = user.email;
                            attendance.Userwise_Working_Day__c = uwMap.get(user.Id).Id;
                            attendance.Cut_off_Time__c = cutOffTime;
                            attendanceLst.add(attendance);
                        }
                    }
                    else{
                        Attendance__c attendance = new Attendance__c();
                            Time cutOffTime = Time.newInstance(09, 45, 00, 00);
                            attendance.User__c = user.Id;
                            attendance.Date__c = Date.today();
                            attendance.Status__c = 'Week-Off';
                            attendance.Email__c = user.email;
                            attendance.Userwise_Working_Day__c = uwMap.get(user.Id).Id;
                            attendance.Cut_off_Time__c = cutOffTime;
                            attendanceLst.add(attendance);
                    }
                }
            }
        }
        if(!attendanceLst.isEmpty()){insert attendanceLst;}
        
    }
    public void finish(Database.BatchableContext bc){
        // execute any post-processing operations
    }
}