force-app/main/default/objects/Attendance__c/Attendance__c.object-meta.xml
<CustomObject>
    <label>Attendance</label>
    <nameField>
        <displayFormat>Att-{0000}</displayFormat>
        <label>Attendance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendance__c/fields/Check_In_Time__c.field-meta.xml
<CustomField>
    <fullName>Check_In_Time__c</fullName>
    <label>Check-In Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Cut_off_Time__c.field-meta.xml
<CustomField>
    <fullName>Cut_off_Time__c</fullName>
    <label>Cut-off Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Present</fullName>
            </value>
            <value>
                <fullName>Absent</fullName>
                <default>true</default>
                <label>Absent</label>
            </value>
            <value>
                <fullName>Leave - In Approval</fullName>
            </value>
            <value>
                <fullName>Leave - Approved</fullName>
            </value>
            <value>
                <fullName>Holiday</fullName>
            </value>
            <value>
                <fullName>Week-Off</fullName>
            </value>
            <value>
                <fullName>Casual Leave</fullName>
            </value>
            <value>
                <fullName>Sick Leave</fullName>
            </value>
            <value>
                <fullName>Half Day</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Attendance1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Holiday_Calander__c/Holiday_Calander__c.object-meta.xml
<CustomObject>
    <label>Holiday Calander</label>
    <nameField>
        <label>Holiday Calander Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Holiday Calanders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Holiday_Calander__c/fields/Holiday_Dates__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Dates__c</fullName>
    <label>Holiday Dates</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Holiday_Calander__c/fields/Holiday_Month__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Month__c</fullName>
    <label>Holiday Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>January</fullName>
            </value>
            <value>
                <fullName>February</fullName>
            </value>
            <value>
                <fullName>March</fullName>
            </value>
            <value>
                <fullName>April</fullName>
            </value>
            <value>
                <fullName>May</fullName>
            </value>
            <value>
                <fullName>June</fullName>
            </value>
            <value>
                <fullName>July</fullName>
            </value>
            <value>
                <fullName>August</fullName>
            </value>
            <value>
                <fullName>September</fullName>
            </value>
            <value>
                <fullName>October</fullName>
            </value>
            <value>
                <fullName>November</fullName>
            </value>
            <value>
                <fullName>December</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Holiday_Calander__c/fields/Zone__c.field-meta.xml
<CustomField>
    <fullName>Zone__c</fullName>
    <label>Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>South-AP &amp; TS</fullName>
            </value>
            <value>
                <fullName>South-Tamilnadu</fullName>
            </value>
            <value>
                <fullName>South-Karnataka</fullName>
            </value>
            <value>
                <fullName>South-Kerala</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Dealing_in_Categories__c.field-meta.xml
<CustomField>
    <fullName>Dealing_in_Categories__c</fullName>
    <label>Dealing in Categories</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Grade__c.field-meta.xml
<CustomField>
    <fullName>Grade__c</fullName>
    <label>Grade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>S0</fullName>
            </value>
            <value>
                <fullName>S1</fullName>
            </value>
            <value>
                <fullName>S2</fullName>
            </value>
            <value>
                <fullName>S3</fullName>
            </value>
            <value>
                <fullName>E1</fullName>
            </value>
            <value>
                <fullName>E2</fullName>
            </value>
            <value>
                <fullName>E3</fullName>
            </value>
            <value>
                <fullName>E4</fullName>
            </value>
            <value>
                <fullName>M1</fullName>
            </value>
            <value>
                <fullName>M2</fullName>
            </value>
            <value>
                <fullName>M3</fullName>
            </value>
            <value>
                <fullName>M4</fullName>
            </value>
            <value>
                <fullName>M5</fullName>
            </value>
            <value>
                <fullName>M6</fullName>
            </value>
            <value>
                <fullName>M7</fullName>
            </value>
            <value>
                <fullName>M8 &amp; Above</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Related_To_Business__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Business__c</fullName>
    <label>Related To Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>Export</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Zone__c.field-meta.xml
<CustomField>
    <fullName>Zone__c</fullName>
    <label>Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>South-Kerala</fullName>
            </value>
            <value>
                <fullName>South-Karnataka</fullName>
            </value>
            <value>
                <fullName>South-Tamilnadu</fullName>
            </value>
            <value>
                <fullName>South-AP &amp; TS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Product_Categories.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0.8mm/HPL</fullName>
    </customValue>
    <customValue>
        <fullName>1 mm/HPL</fullName>
    </customValue>
    <customValue>
        <fullName>Cubicles</fullName>
    </customValue>
    <customValue>
        <fullName>Compact</fullName>
    </customValue>
    <customValue>
        <fullName>Fascia</fullName>
    </customValue>
    <customValue>
        <fullName>Granex</fullName>
    </customValue>
    <customValue>
        <fullName>Prelam</fullName>
    </customValue>
    <masterLabel>Product Categories</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HandleAttandenceController_Test.cls
@isTest
public class HandleAttandenceController_Test {
    @testSetup
    static void testSetup(){
        Profile pf= [Select Id from profile where Name='System Administrator']; 
        
        User u = new User();
        u.Grade__c = 'E1';
        u.FirstName = 'test';
        u.LastName = 'test';
        u.Alias = 'ttest';
        u.Email = 'test@gmail.com';
        u.Username = 'test@gmail.com.stylam2022';
        u.CommunityNickname = 'test1';
        //u.Related_To_Business__c = 'Domestic';
        //u.Dealing_in_Categories__c = 'Cubicles';
        u.TimeZoneSidKey = 'America/Los_Angeles';
        u.EmailEncodingKey = 'UTF-8';
        u.LanguageLocaleKey = 'en_US';
        u.LocaleSidKey = 'en_US';
        u.ProfileId = pf.Id;
        u.Grade__c = 'M1';
        INSERT u;
        Holiday_Calander__c holiday = new Holiday_Calander__c ();
        holiday.Holiday_Dates__c = '1';
        holiday.Holiday_Month__c = String.valueOF(System.today().month());
        holiday.Zone__c = 'East';
        insert holiday;
        Time checkTime=Time.newInstance(12, 20, 00,00);
        Datetime NewDate= Datetime.newInstance(System.today(), checkTime);
        Attendance__c attendanceObj= new Attendance__c();
        attendanceObj.Status__c='Absent';
        attendanceObj.User__c=userinfo.getUserId();
        attendanceObj.Check_In_Time__c= NewDate;
        attendanceObj.Date__c= system.today();
        insert attendanceObj;
    }
    static testMethod void test1(){
        Attendance__c att = [Select id,Status__c,User__c,Check_In_Time__c,Date__c from Attendance__c];
        att.Status__c = 'Half Day';
        update att;
    	HandleAttandenceController.checkCurrentStatus();    
    }
    static testMethod void test2(){
        Attendance__c att = [Select id,Status__c,User__c,Check_In_Time__c,Date__c from Attendance__c];
        att.Status__c = 'Absent';
        att.Check_In_Time__c = null;
        att.Cut_off_Time__c = Datetime.now().addDays(-1).time();
        update att;
    	HandleAttandenceController.checkCurrentStatus();    
    }
    static testMethod void test3(){
        Attendance__c att = [Select id,Status__c,User__c,Check_In_Time__c,Date__c from Attendance__c];
        att.Status__c = 'Absent';
        att.Check_In_Time__c = null;
        update att;
    	HandleAttandenceController.checkCurrentStatus();
        HandleAttandenceController.doPunchIn();
        //HandleAttandenceController.halfDay();
    }
    static testMethod void test4(){
    	Attendance__c att = [Select id,Status__c,User__c,Check_In_Time__c,Date__c from Attendance__c];
        att.Status__c = 'Present';
        att.Check_In_Time__c = null;
        update att;
        HandleAttandenceController.doPunchOut();
    }

}