force-app/main/default/objects/Attendance__c/Attendance__c.object-meta.xml
<CustomObject>
    <label>Attendance</label>
    <nameField>
        <displayFormat>Att-{0000}</displayFormat>
        <label>Attendance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendance__c/fields/Check_In_Time__c.field-meta.xml
<CustomField>
    <fullName>Check_In_Time__c</fullName>
    <label>Check-In Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Cut_off_Time__c.field-meta.xml
<CustomField>
    <fullName>Cut_off_Time__c</fullName>
    <label>Cut-off Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Present</fullName>
            </value>
            <value>
                <fullName>Absent</fullName>
                <default>true</default>
                <label>Absent</label>
            </value>
            <value>
                <fullName>Leave - In Approval</fullName>
            </value>
            <value>
                <fullName>Leave - Approved</fullName>
            </value>
            <value>
                <fullName>Holiday</fullName>
            </value>
            <value>
                <fullName>Week-Off</fullName>
            </value>
            <value>
                <fullName>Casual Leave</fullName>
            </value>
            <value>
                <fullName>Sick Leave</fullName>
            </value>
            <value>
                <fullName>Half Day</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Attendance1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Holiday_Calander__c/Holiday_Calander__c.object-meta.xml
<CustomObject>
    <label>Holiday Calander</label>
    <nameField>
        <label>Holiday Calander Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Holiday Calanders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Holiday_Calander__c/fields/Holiday_Dates__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Dates__c</fullName>
    <label>Holiday Dates</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Holiday_Calander__c/fields/Holiday_Month__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Month__c</fullName>
    <label>Holiday Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>January</fullName>
            </value>
            <value>
                <fullName>February</fullName>
            </value>
            <value>
                <fullName>March</fullName>
            </value>
            <value>
                <fullName>April</fullName>
            </value>
            <value>
                <fullName>May</fullName>
            </value>
            <value>
                <fullName>June</fullName>
            </value>
            <value>
                <fullName>July</fullName>
            </value>
            <value>
                <fullName>August</fullName>
            </value>
            <value>
                <fullName>September</fullName>
            </value>
            <value>
                <fullName>October</fullName>
            </value>
            <value>
                <fullName>November</fullName>
            </value>
            <value>
                <fullName>December</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Holiday_Calander__c/fields/Zone__c.field-meta.xml
<CustomField>
    <fullName>Zone__c</fullName>
    <label>Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>South-AP &amp; TS</fullName>
            </value>
            <value>
                <fullName>South-Tamilnadu</fullName>
            </value>
            <value>
                <fullName>South-Karnataka</fullName>
            </value>
            <value>
                <fullName>South-Kerala</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Zone__c.field-meta.xml
<CustomField>
    <fullName>Zone__c</fullName>
    <label>Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>South-Kerala</fullName>
            </value>
            <value>
                <fullName>South-Karnataka</fullName>
            </value>
            <value>
                <fullName>South-Tamilnadu</fullName>
            </value>
            <value>
                <fullName>South-AP &amp; TS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HandleAttandenceController.cls
public with sharing class HandleAttandenceController {
    @AuraEnabled(Cacheable = true)
    public static String checkCurrentStatus(){
        Date currentDate = system.today();
        String status;
        List<String> dayList = new List<String>();
        List<String> zoneList = new List<String>();
        Boolean holidayCheck = false;
        User currentUser = [Select Id,FirstName,LastName,Zone__c FROM User WHERE Id =: UserInfo.getUserId() AND isActive = true];
        List<Holiday_Calander__c> holidayList = [Select Id,Name,Holiday_Dates__c,Holiday_Month__c,Zone__c FROM Holiday_Calander__c WHERE (Holiday_Month__c =: String.valueOf(currentDate.month()))];                                          
        if(!holidayList.isEmpty()){
            for(Holiday_Calander__c hc : holidayList){
                dayList = hc.Holiday_Dates__c.split(';');
                zoneList = hc.Zone__c.split(';');
                if(dayList.contains(String.valueOf(currentDate.day())) && zoneList.contains(String.valueOf(hc.Zone__c))){
                    holidayCheck = true;
                    status = 'None';
                }
            }
        }
        if(holidayList.isEmpty() || holidayCheck == false){
            Attendance__c attendanceRec = [SELECT Id, Name, Date__c, User__c,Cut_off_Time__c,Status__c,Check_In_Time__c,Check_Out_Time__c FROM Attendance__c WHERE Date__c =: currentDate AND User__c =: UserInfo.getUserId()];
            Boolean checkout = false;
            Time halfDayCheckTime = Time.newInstance(13, 30, 0, 00);
            if(attendanceRec.Cut_off_Time__c < system.now().time()){
                checkout = true;
            }
            system.debug('checkout'+checkout);

            if(attendanceRec.Status__c == 'Leave - Approved (First Half)'){
                if(system.now().time() < halfDayCheckTime){
                    status = 'None';
                }
                else if(system.now().time() > halfDayCheckTime){
                    status = 'halfDay';
                }
            }
            else if(attendanceRec.Status__c == 'Leave - Approved (Second Half)'){
                if(system.now().time() < halfDayCheckTime){
                    status = 'halfDay';
                }
                else if(system.now().time() > halfDayCheckTime){
                    status = 'None';
                }
            }
            else if((attendanceRec.Status__c == 'Present' || attendanceRec.Status__c == 'Leave - Approved (First Half)' || attendanceRec.Status__c == 'Leave - Approved (Second Half)') && attendanceRec.Check_In_Time__c != Null && attendanceRec.Check_Out_Time__c == NULL){
                status = 'punchout';
            }
            else if(attendanceRec.Status__c == 'Absent' && attendanceRec.Check_In_Time__c == Null && attendanceRec.Check_Out_Time__c == NULL && checkout == True){
                status = 'halfDay';
            }
            else if(attendanceRec.Status__c == 'Absent' && attendanceRec.Check_In_Time__c == Null && attendanceRec.Check_Out_Time__c == NULL && checkout == False){
                status = 'both';
            }
            system.debug('status$$$$$$$'+status);	            
        }
        return status;
    }
    @AuraEnabled
    public static void doPunchIn() { 
        Date todayDate = system.today();
        Attendance__c attendanceRec = [SELECT Id,Name,Status__c,Check_In_Time__c,Cut_off_Time__c FROM Attendance__c WHERE Date__c =: todayDate AND Status__c = 'Absent' AND User__c =: UserInfo.getUserId()];
        if(attendanceRec != Null){
            attendanceRec.Status__c = 'Present';
            attendanceRec.Check_In_Time__c = system.now();
            update attendanceRec;
        }
    }
    @AuraEnabled
    public static void doPunchOut() { 
        Date todayDate = system.today();
        Attendance__c attendanceRec = [SELECT Id,Name,Status__c,Check_Out_Time__c FROM Attendance__c WHERE Date__c =: todayDate AND (Status__c = 'Present' OR Status__c = 'Half Day') AND User__c	=: UserInfo.getUserId()];
        if(attendanceRec != Null){
            //attendanceRec.Status__c = 'Present';
            attendanceRec.Check_Out_Time__c = system.now();
            update attendanceRec;
        }
    }
    @AuraEnabled
    public static void halfDay() { 
        Date todayDate = system.today();
        Attendance__c attendanceRec = [SELECT Id,Name,Status__c,Check_In_Time__c FROM Attendance__c WHERE Date__c =: todayDate  AND Status__c = 'Absent' AND User__c =: UserInfo.getUserId()];
        if(attendanceRec != Null){
            //attendanceRec.Status__c = 'Half Day';
            attendanceRec.Check_In_Time__c = system.now();
            update attendanceRec;
        }
    }
}