force-app/main/default/objects/Holiday_Calander__c/Holiday_Calander__c.object-meta.xml
<CustomObject>
    <label>Holiday Calander</label>
    <nameField>
        <label>Holiday Calander Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Holiday Calanders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Holiday_Calander__c/fields/Holiday_Dates__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Dates__c</fullName>
    <label>Holiday Dates</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Holiday_Calander__c/fields/Holiday_Month__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Month__c</fullName>
    <label>Holiday Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>January</fullName>
            </value>
            <value>
                <fullName>February</fullName>
            </value>
            <value>
                <fullName>March</fullName>
            </value>
            <value>
                <fullName>April</fullName>
            </value>
            <value>
                <fullName>May</fullName>
            </value>
            <value>
                <fullName>June</fullName>
            </value>
            <value>
                <fullName>July</fullName>
            </value>
            <value>
                <fullName>August</fullName>
            </value>
            <value>
                <fullName>September</fullName>
            </value>
            <value>
                <fullName>October</fullName>
            </value>
            <value>
                <fullName>November</fullName>
            </value>
            <value>
                <fullName>December</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Holiday_Calander__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
            <value>
                <fullName>2034</fullName>
            </value>
            <value>
                <fullName>2035</fullName>
            </value>
            <value>
                <fullName>2036</fullName>
            </value>
            <value>
                <fullName>2037</fullName>
            </value>
            <value>
                <fullName>2038</fullName>
            </value>
            <value>
                <fullName>2039</fullName>
            </value>
            <value>
                <fullName>2040</fullName>
            </value>
            <value>
                <fullName>2041</fullName>
            </value>
            <value>
                <fullName>2042</fullName>
            </value>
            <value>
                <fullName>2043</fullName>
            </value>
            <value>
                <fullName>2044</fullName>
            </value>
            <value>
                <fullName>2045</fullName>
            </value>
            <value>
                <fullName>2046</fullName>
            </value>
            <value>
                <fullName>2047</fullName>
            </value>
            <value>
                <fullName>2048</fullName>
            </value>
            <value>
                <fullName>2049</fullName>
            </value>
            <value>
                <fullName>2050</fullName>
            </value>
            <value>
                <fullName>2051</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Holiday_Calander__c/fields/Zone__c.field-meta.xml
<CustomField>
    <fullName>Zone__c</fullName>
    <label>Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>South-AP &amp; TS</fullName>
            </value>
            <value>
                <fullName>South-Tamilnadu</fullName>
            </value>
            <value>
                <fullName>South-Karnataka</fullName>
            </value>
            <value>
                <fullName>South-Kerala</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Dealing_in_Categories__c.field-meta.xml
<CustomField>
    <fullName>Dealing_in_Categories__c</fullName>
    <label>Dealing in Categories</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Categories</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Grade__c.field-meta.xml
<CustomField>
    <fullName>Grade__c</fullName>
    <label>Grade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>S0</fullName>
            </value>
            <value>
                <fullName>S1</fullName>
            </value>
            <value>
                <fullName>S2</fullName>
            </value>
            <value>
                <fullName>S3</fullName>
            </value>
            <value>
                <fullName>E1</fullName>
            </value>
            <value>
                <fullName>E2</fullName>
            </value>
            <value>
                <fullName>E3</fullName>
            </value>
            <value>
                <fullName>E4</fullName>
            </value>
            <value>
                <fullName>M1</fullName>
            </value>
            <value>
                <fullName>M2</fullName>
            </value>
            <value>
                <fullName>M3</fullName>
            </value>
            <value>
                <fullName>M4</fullName>
            </value>
            <value>
                <fullName>M5</fullName>
            </value>
            <value>
                <fullName>M6</fullName>
            </value>
            <value>
                <fullName>M7</fullName>
            </value>
            <value>
                <fullName>M8 &amp; Above</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Related_To_Business__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Business__c</fullName>
    <label>Related To Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>Export</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Zone__c.field-meta.xml
<CustomField>
    <fullName>Zone__c</fullName>
    <label>Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>South-Kerala</fullName>
            </value>
            <value>
                <fullName>South-Karnataka</fullName>
            </value>
            <value>
                <fullName>South-Tamilnadu</fullName>
            </value>
            <value>
                <fullName>South-AP &amp; TS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Userwise_Working_Day__c/Userwise_Working_Day__c.object-meta.xml
<CustomObject>
    <label>Userwise Working Day</label>
    <nameField>
        <label>Parent Attendance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Userwise Working Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Userwise_Working_Day__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Userwise_Working_Days</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Userwise_Working_Day__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
            <value>
                <fullName>2034</fullName>
            </value>
            <value>
                <fullName>2035</fullName>
            </value>
            <value>
                <fullName>2036</fullName>
            </value>
            <value>
                <fullName>2037</fullName>
            </value>
            <value>
                <fullName>2038</fullName>
            </value>
            <value>
                <fullName>2039</fullName>
            </value>
            <value>
                <fullName>2040</fullName>
            </value>
            <value>
                <fullName>2041</fullName>
            </value>
            <value>
                <fullName>2042</fullName>
            </value>
            <value>
                <fullName>2043</fullName>
            </value>
            <value>
                <fullName>2044</fullName>
            </value>
            <value>
                <fullName>2045</fullName>
            </value>
            <value>
                <fullName>2046</fullName>
            </value>
            <value>
                <fullName>2047</fullName>
            </value>
            <value>
                <fullName>2048</fullName>
            </value>
            <value>
                <fullName>2049</fullName>
            </value>
            <value>
                <fullName>2050</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Product_Categories.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0.8mm/HPL</fullName>
    </customValue>
    <customValue>
        <fullName>1 mm/HPL</fullName>
    </customValue>
    <customValue>
        <fullName>Cubicles</fullName>
    </customValue>
    <customValue>
        <fullName>Compact</fullName>
    </customValue>
    <customValue>
        <fullName>Fascia</fullName>
    </customValue>
    <customValue>
        <fullName>Granex</fullName>
    </customValue>
    <customValue>
        <fullName>Prelam</fullName>
    </customValue>
    <masterLabel>Product Categories</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CreateDailyAttendance_Test.cls
@istest
public class CreateDailyAttendance_Test {
    public static testMethod void testschedule() {
        Test.StartTest();
        Profile pf= [Select Id from profile where Name='System Administrator']; 
        User u = new User();
        u.Grade__c = 'E1';
        u.FirstName = 'test';
        u.LastName = 'test';
        u.Alias = 'ttest';
        u.Email = 'test@gmail.com';
        u.Username = 'test@gmail.com.stylam202204';
        u.CommunityNickname = 'test';
        u.Related_To_Business__c = 'Domestic';
        u.Dealing_in_Categories__c = 'Cubicles';
        u.TimeZoneSidKey = 'America/Los_Angeles';
        u.EmailEncodingKey = 'UTF-8';
        u.LanguageLocaleKey = 'en_US';
        u.LocaleSidKey = 'en_US';
        u.ProfileId = pf.Id;
        u.IsActive = true;
        INSERT u;
        
        Userwise_Working_Day__c uwd =New Userwise_Working_Day__c();
        uwd.Name = 'Test';
        uwd.User__c = u.id;
        integer Year = system.today().year();
        uwd.Year__c = string.valueOf(Year);
        insert uwd;
        
        main(u.id);
        
        CreateDailyAttendance sh1 = new CreateDailyAttendance();
        Database.executeBatch(sh1);
        Test.stopTest(); 
    }
    public static testMethod void testMethod_01() {
        Test.StartTest();
        Profile pf= [Select Id from profile where Name='System Administrator']; 
        User u = new User();
        u.Grade__c = 'E1';
        u.FirstName = 'test';
        u.LastName = 'test';
        u.Alias = 'ttest';
        u.Email = 'test@gmail.com';
        u.Username = 'test@gmail.com.stylam202204';
        u.CommunityNickname = 'test';
        u.Related_To_Business__c = 'Domestic';
        u.Dealing_in_Categories__c = 'Cubicles';
        u.TimeZoneSidKey = 'America/Los_Angeles';
        u.EmailEncodingKey = 'UTF-8';
        u.LanguageLocaleKey = 'en_US';
        u.LocaleSidKey = 'en_US';
        u.ProfileId = pf.Id;
        u.IsActive = true;
        INSERT u;
        
        Userwise_Working_Day__c uwd =New Userwise_Working_Day__c();
        uwd.Name = 'Test';
        uwd.User__c = u.id;
        integer Year = system.today().year();
        uwd.Year__c = string.valueOf(Year);
        insert uwd;
        
        Holiday_Calander__c holidayCalender= New Holiday_Calander__c();
        holidayCalender.Name = 'Test';
        holidayCalender.Holiday_Dates__c = '4; 16; 23';
        holidayCalender.Holiday_Month__c = '11';
        holidayCalender.Zone__c ='South; West';
        insert holidayCalender;
        
        main(u.id);
        
        CreateDailyAttendance sh1 = new CreateDailyAttendance();
        Database.executeBatch(sh1);
        Test.stopTest(); 
    }
    public static testMethod void testMethod_02() {
        Test.StartTest();
        Profile pf= [Select Id from profile where Name='System Administrator']; 
        User u = new User();
        u.Grade__c = 'E1';
        u.FirstName = 'test';
        u.LastName = 'test';
        u.Alias = 'ttest';
        u.Email = 'test@gmail.com';
        u.Username = 'test@gmail.com.stylam202204';
        u.CommunityNickname = 'test';
        u.Related_To_Business__c = 'Domestic';
        u.Dealing_in_Categories__c = 'Cubicles';
        u.TimeZoneSidKey = 'America/Los_Angeles';
        u.EmailEncodingKey = 'UTF-8';
        u.LanguageLocaleKey = 'en_US';
        u.LocaleSidKey = 'en_US';
        u.ProfileId = pf.Id;
        u.Zone__c ='South';
        u.IsActive = true;
        INSERT u;
        
        Userwise_Working_Day__c uwd =New Userwise_Working_Day__c();
        uwd.Name = 'Test';
        uwd.User__c = u.id;
        integer Year = system.today().year();
        integer Month = system.today().Month();
        integer day = system.today().day();
        system.debug('Year----'+ Year);
        system.debug('day----'+ day);
        uwd.Year__c = string.valueOf(Year);
        insert uwd;
        
        Holiday_Calander__c holidayCalender= New Holiday_Calander__c();
        holidayCalender.Name = 'Test';
        holidayCalender.Holiday_Dates__c = string.valueOf(day);
        holidayCalender.Holiday_Month__c = string.valueOf(Month);
        holidayCalender.Zone__c ='South; West';
        holidayCalender.Year__c =string.valueOf(Year);
        insert holidayCalender;
        
        main(u.id);
        
        CreateDailyAttendance sh1 = new CreateDailyAttendance();
        Database.executeBatch(sh1);
        Test.stopTest(); 
    }
    
    public static testMethod void testMethod_03() {
        Test.StartTest();
        Profile pf= [Select Id from profile where Name='System Administrator']; 
        User u = new User();
        u.Grade__c = 'E1';
        u.FirstName = 'test';
        u.LastName = 'test';
        u.Alias = 'ttest';
        u.Email = 'test@gmail.com';
        u.Username = 'test@gmail.com.stylam202204';
        u.CommunityNickname = 'test';
        u.Related_To_Business__c = 'Domestic';
        u.Dealing_in_Categories__c = 'Cubicles';
        u.TimeZoneSidKey = 'America/Los_Angeles';
        u.EmailEncodingKey = 'UTF-8';
        u.LanguageLocaleKey = 'en_US';
        u.LocaleSidKey = 'en_US';
        u.ProfileId = pf.Id;
        u.Zone__c ='South';
        u.IsActive = true;
        INSERT u;
        
        Userwise_Working_Day__c uwd =New Userwise_Working_Day__c();
        uwd.Name = 'Test';
        uwd.User__c = u.id;
        integer Year = system.today().year();
        integer Month = system.today().Month();
        integer day = system.today().day();
        system.debug('Year----'+ Year);
        system.debug('day----'+ day);
        uwd.Year__c = string.valueOf(Year);
        insert uwd;
        
        Holiday_Calander__c holidayCalender= New Holiday_Calander__c();
        holidayCalender.Name = 'Test';
        holidayCalender.Holiday_Dates__c = string.valueOf(day);
        holidayCalender.Holiday_Month__c = string.valueOf(Month);
        holidayCalender.Zone__c ='West';
        holidayCalender.Year__c =string.valueOf(Year);
        insert holidayCalender;
        
        main(u.id);
        
        CreateDailyAttendance sh1 = new CreateDailyAttendance();
        Database.executeBatch(sh1);
        Test.stopTest(); 
    }

    
    @future
    public static void main(String userId){
        PermissionSet newPermission = [SELECT Id FROM PermissionSet WHERE Name = 'Mark_Attendance'];
        PermissionSetAssignment psa = new PermissionSetAssignment();
        psa.AssigneeId = userId;
        psa.PermissionSetId = newPermission.Id;
        INSERT psa;
    }
}